

export const assetPositionMap = {
    "Bow": {
        "Gotie": { top: 0, left: -5, width: 90, height: 90, transform: [{ rotate: '25deg' }]  },
        "Sunsetegg": { top: 0, left: -5, width: 90, height: 90, transform: [{ rotate: '25deg' }]  },
        "Rainbowegg": { top: 0, left: -5, width: 90, height: 90, transform: [{ rotate: '25deg' }]  },
        "Emmei": { top: 0, left: -5, width: 90, height: 90, transform: [{ rotate: '25deg' }]  },
        "Pinkie": { top: 0, left: -5, width: 90, height: 90, transform: [{ rotate: '25deg' }]  },
        "Gotie Gold": { top: -5, left: -15, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Gotiebow": { top: -5, left: -15, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Gotiestripes": { top: -5, left: -15, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Gotie Pink": { top: -5, left: -15, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Gotie Blue": { top: -5, left: -15, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Youngbow": { top: -5, left:5, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Youngstr": { top: -5, left:5, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Youngpi": { top: -5, left:5, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Youngie": { top: -5, left:5, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Youngemi": { top: -5, left:5, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Bubblgam": { top: -5, left: 5, width: 80, height: 80, transform: [{ rotate: '20deg' }] },
        "Bubblgum": { top: -5, left: 5, width: 80, height: 80, transform: [{ rotate: '20deg' }] },
        "Bubblgom": { top: -5, left: 5, width: 80, height: 80, transform: [{ rotate: '20deg' }] },
        "Rainbow": { top: -5, left: 5, width: 80, height: 80, transform: [{ rotate: '20deg' }] },
        "Sunset": { top: -5, left: 5, width: 80, height: 80, transform: [{ rotate: '20deg' }] },
    },
    "Santa Hat": {
        "Gotie": { top: 0, left: 0, width: 70, height: 70, transform: [{ rotate: '25deg' }] },
        "Sunsetegg": { top: 0, left: 0, width: 70, height: 70, transform: [{ rotate: '25deg' }] },
        "Rainbowegg": { top: 0, left: 0, width: 70, height: 70, transform: [{ rotate: '25deg' }] },
        "Emmei": { top: 0, left: 0, width: 70, height: 70, transform: [{ rotate: '25deg' }] },
        "Pinkie": { top: 0, left: 0, width: 70, height: 70, transform: [{ rotate: '25deg' }] },
        "Gotie Gold": { top: -20, left: -10, width: 80, height: 80, transform: [{ rotate: '20deg' }] },
        "Gotiebow": { top: -20, left: -10, width: 80, height: 80, transform: [{ rotate: '20deg' }] },
        "Gotiestripes": { top: -20, left: -10, width: 80, height: 80, transform: [{ rotate: '20deg' }] },
        "Gotie Pink": { top: -20, left: -10, width: 80, height: 80, transform: [{ rotate: '20deg' }] },
        "Gotie Blue": { top: -20, left: -10, width: 80, height: 80, transform: [{ rotate: '20deg' }] },
        "Youngbow": { top: -5, left: 25, width: 80, height: 80, transform: [{ rotate: '25deg' }] },
        "Youngstr": { top: -5, left: 25, width: 80, height: 80, transform: [{ rotate: '25deg' }] },
        "Youngpi": { top: -5, left: 25, width: 80, height: 80, transform: [{ rotate: '25deg' }] },
        "Youngie": { top: -5, left: 25, width: 80, height: 80, transform: [{ rotate: '25deg' }] },
        "Youngemi": { top: -5, left: 25, width: 80, height: 80, transform: [{ rotate: '25deg' }] },
        "Bubblgam": { top: -10, left: -50, width: 70, height: 70, transform: [{ rotate: '20deg' }] },
        "Bubblgum": { top: -10, left: -50, width: 70, height: 70, transform: [{ rotate: '20deg' }] },
        "Bubblgom": { top: -10, left: -50, width: 70, height: 70, transform: [{ rotate: '20deg' }] },
        "Rainbow": { top: -10, left: -50, width: 70, height: 70, transform: [{ rotate: '20deg' }] },
        "Sunset": { top: -10, left: -50, width: 70, height: 70, transform: [{ rotate: '20deg' }] },
    },
    "Confetti": {
        "Gotie": { top: -10, left: 0, width: 90, height: 90, transform: [{ rotate: '25deg' }] },
        "Sunsetegg": { top: -10, left: 0, width: 90, height: 90, transform: [{ rotate: '25deg' }] },
        "Rainbowegg": { top: -10, left: 0, width: 90, height: 90, transform: [{ rotate: '25deg' }] },
        "Emmei": { top: -10, left: 0, width: 90, height: 90, transform: [{ rotate: '25deg' }] },
        "Pinkie": { top: -10, left: 0, width: 90, height: 90, transform: [{ rotate: '25deg' }] },
        "Gotie Gold": { top: -10, left: -5, width: 70, height: 70, transform: [{ rotate: '20deg' }] },
        "Gotiebow": { top: -10, left: -5, width: 70, height: 70, transform: [{ rotate: '20deg' }] },
        "Gotiestripes": { top: -10, left: -5, width: 70, height: 70, transform: [{ rotate: '20deg' }] },
        "Gotie Pink": { top: -10, left: -5, width: 70, height: 70, transform: [{ rotate: '20deg' }] },
        "Gotie Blue": { top: -10, left: -5, width: 70, height: 70, transform: [{ rotate: '20deg' }] },
        "Youngbow": { top: -15, left: 20, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Youngstr": { top: -15, left: 20, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Youngpi": { top: -15, left: 20, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Youngie": { top: -15, left: 20, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Youngemi": { top: -15, left: 20, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Bubblgam": { top: -20, left: 10, width: 80, height: 80, transform: [{ rotate: '20deg' }] },
        "Bubblgum": { top: -20, left: 10, width: 80, height: 80, transform: [{ rotate: '20deg' }] },
        "Bubblgom": { top: -20, left: 10, width: 80, height: 80, transform: [{ rotate: '20deg' }] },
        "Rainbow": { top: -20, left: 10, width: 80, height: 80, transform: [{ rotate: '20deg' }] },
        "Sunset": { top: -20, left: 10, width: 80, height: 80, transform: [{ rotate: '20deg' }] },
    },
    "Beannie": {
        "Gotie": { top: 0, left: -20, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Sunsetegg": { top: 0, left: -20, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Rainbowegg": { top: 0, left: -20, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Emmei": { top: 0, left: -20, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Pinkie": { top: 0, left: -20, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Gotie Gold": { top: -10, left: -20, width: 80, height: 80, transform: [{ rotate: '15deg' }] },
        "Gotiebow": { top: -10, left: -20, width: 80, height: 80, transform: [{ rotate: '15deg' }] },
        "Gotiestripes": { top: -10, left: -20, width: 80, height: 80, transform: [{ rotate: '15deg' }] },
        "Gotie Pink": { top: -10, left: -20, width: 80, height: 80, transform: [{ rotate: '15deg' }] },
        "Gotie Blue": { top: -10, left: -20, width: 80, height: 80, transform: [{ rotate: '15deg' }] },
        "Youngbow": { top: -3, left: 15, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Youngstr": { top: -3, left: 15, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Youngpi": { top: -3, left: 15, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Youngie": { top: -3, left: 15, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Youngemi": { top: -3, left: 15, width: 90, height: 90, transform: [{ rotate: '20deg' }] },
        "Bubblgam": { top: 0, left: 10, width: 70, height: 70, transform: [{ rotate: '20deg' }] },
        "Bubblgum": { top: 0, left: 10, width: 70, height: 70, transform: [{ rotate: '20deg' }] },
        "Bubblgom": { top: 0, left: 10, width: 70, height: 70, transform: [{ rotate: '20deg' }] },
        "Rainbow": { top: 0, left: 10, width: 70, height: 70, transform: [{ rotate: '20deg' }] },
        "Sunset": { top: 0, left: 10, width: 70, height: 70, transform: [{ rotate: '20deg' }] },
    },
};
